---
openapi: 3.0.2
info:
  title: Customer API
  description: This is the Customer API. It provides RESTful operations for Customer data.
  contact:
    name: Richard Monson-Haefel
    url: http://www.pluralsight.com
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0-oas3
servers:
- url: http://api.globlmantics.com/cmr/v1
- url: https://api.globlmantics.com/cmr/v1
security:
- basicAuth: []
paths:
  /customer:
    get:
      summary: reads a customer's data
      description: This operation provides a view of the customers data in JSON. The operation uses the customers id to identify the customer  in a query string.
      operationId: getCustomer
      parameters:
      - name: custsomerId
        in: query
        description: pass a customer id to get customer data
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        "404":
          description: employee with this id does not exist.
    post:
      summary: adds a new customer
      description: Add a new customer to the system
      operationId: addCustomer
      requestBody:
        description: the new customer data in JSON format
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Success. Body includes the auto-generated key for the new customer
          content:
            text/plain:
              schema:
                type: integer
        "405":
          description: Invalid Input
  /customer/{customerId}:
    put:
      summary: update existing customer
      description: Updates an existing customer with new data
      operationId: updateCustomer
      parameters:
      - name: customerId
        in: path
        description: the id of the customer to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      requestBody:
        description: the updated customer data in JSON format
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        "200":
          description: Success.
        "404":
          description: Customer Not Found
        "500":
          description: Internal Server Error
    delete:
      summary: delete an existing customer
      description: Deletes an existing customer in the system.
      operationId: deleteCustomer
      parameters:
      - name: customerId
        in: path
        description: the id of the customer to update
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: The customer was deleted
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Customer'
        "404":
          description: Customer Not Found
        "500":
          description: Internal Server Error
components:
  schemas:
    Customer:
      type: object
      properties:
        customerId:
          type: integer
        accountValue:
          type: number
        customerName:
          type: string
        active:
          type: boolean
        address:
          $ref: '#/components/schemas/Customer_address'
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Customer_contacts'
    Customer_address:
      type: object
      properties:
        name:
          type: string
        street:
          type: string
        city:
          type: string
        state:
          type: string
        zip:
          type: string
    Customer_contacts:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        phone:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
